### ISSUE TITLE
Does the closure filter need a sync bound?

### ISSUE THREAD

**Issue by najamelan** [najamelan/pharos#6]
@syntacticsugarglider Thanks for your interest in pharos. I saw you needed a sync bound on the closure filter. I wondered in what situation did you need this and do you think it would be good to add that bound to the released version of pharos? It obviously would reject certain closures if that bound was added, that's why I'm interested in your feedback to better understand user scenarios.

**Comment by syntacticsugarglider** [comment]
This is no longer necessary for my work and the initial reason for that bound being necessary was very niche. Please disregard.

**Comment by najamelan** [comment]
Ok, thanks for the feedback.
