### ISSUE TITLE
Maintenance status

### ISSUE THREAD

**Issue by gitmalong** [najamelan/pharos#8]
Hi!

I'd like to use the lib and so I am wondering if it is still being maintained as I could not spot any dependency upgrades within the recent month.

Thanks for everything!

**Comment by najamelan** [comment]
Hi, yes it is. I haven't been writing a lot of rust lately because I am doing a front end course. But yes, don't worry, it's maintained and I will go over all my libs soon to give them all a dependency upgrade.

**Comment by gitmalong** [comment]
Awesome! Pharos is exactly what I needed!

**Comment by najamelan** [comment]
Actually, I just looked into it, and the only dependency is the futures library which does not have a breaking change since the last release of pharos, so afaict there is absolutely no use to updating pharos.
